//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYSACH
{
    using System;
    using System.Collections.Generic;
    
    public partial class tHOADON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tHOADON()
        {
            this.tCTHDs = new HashSet<tCTHD>();
        }
    
        public int MaHD { get; set; }
        public Nullable<int> MaDaiLy { get; set; }
        public Nullable<System.DateTime> NgayLapHoaDon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCTHD> tCTHDs { get; set; }
        public virtual tDAILY tDAILY { get; set; }
    }
}
