//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYSACH
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tSACH()
        {
            this.tCTHDs = new HashSet<tCTHD>();
        }
    
        public int MaSach { get; set; }
        public string TenSach { get; set; }
        public string TenTacGia { get; set; }
        public Nullable<double> GiaBia { get; set; }
        public Nullable<double> GiaBanChoDaiLy { get; set; }
        public Nullable<int> MaNhaXuatBan { get; set; }
        public Nullable<int> SoTrang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCTHD> tCTHDs { get; set; }
        public virtual tNHAXUATBAN tNHAXUATBAN { get; set; }
    }
}
